if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
    . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

nitrogen --restore &
dwmblocks &
picom &
mpd &
xclip &
exec dbus-launch dwm
