#!/bin/sh
nitrogen --restore &
picom &
#dunst &
#sxhkd -c ~/.config/sxhkd/sxhkdrc-other &
xclip &
mpd &
#unclutter &
#exec dbus-launch xmonad
#exec dbus-launch bspwm
#exec dbus-launch qtile start
#exec dbus-launch awesome
dwmblocks &
exec dbus-launch dwm
